
backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "site"
    label: "사이트 내용"
    files:
      - file: "data/site.json"
        label: "기본 정보"
        name: "description"
        fields:
          - { label: "설명글", name: "description", widget: "string" }
          - { label: "상세 설명", name: "details", widget: "text" }
          - { label: "버튼 텍스트", name: "button_text", widget: "string" }
